spring:
  datasource:
    master:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: ${prod-master-url}
      username: ${prod-master-username}
      password: ${prod-master-password}
      connection-test-query: SELECT 1
      maximum-pool-size: 8
    slave:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: ${prod-slave-url}
      username: ${prod-slave-username}
      password: ${prod-slave-password}
      connection-test-query: SELECT 2
      maximum-pool-size: 8
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
