server:
  port: 8080
  servlet:
    session:
      tracking-modes: COOKIE

spring:
  datasource:
    master:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost:3306/blog?reconnect=true
      username: root
      password: mariadb
      connection-test-query: SELECT 1
      maximum-pool-size: 8
    slave:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost:3306/blog?reconnect=true
      username: root
      password: mariadb
      connection-test-query: SELECT 2
      maximum-pool-size: 8
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
