spring:
  profiles:
    active: local
  mvc:
    static-path-pattern: /static/**
  devtools:
    livereload:
      enabled: true

springdoc:
  swagger-ui:
    path: /swagger
    operations-sorter: alpha
    tags-sorter: alpha